In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [3]:
#import pandas as pd
import pandas as pd

In [4]:
data = pd.read_csv('DataMLB.csv')
data.head()

Name Team       Position  Height(inches)  Weight(pounds)    Age
0    Adam_Donachie  BAL        Catcher              74           180.0  22.99
1        Paul_Bako  BAL        Catcher              74           215.0  34.69
2  Ramon_Hernandez  BAL        Catcher              72           210.0  30.78
3     Kevin_Millar  BAL  First_Baseman              72           210.0  35.43
4      Chris_Gomez  BAL  First_Baseman              73           188.0  35.71

In [5]:
data_select = pd.read_csv('DataMLB.csv', usecols=['Height(inches)', 'Weight(pounds)', 'Age'])
data_select.head()

Height(inches)  Weight(pounds)    Age
0              74           180.0  22.99
1              74           215.0  34.69
2              72           210.0  30.78
3              72           210.0  35.43
4              73           188.0  35.71

In [6]:
height_in = pd.read_csv('DataMLB.csv', usecols=['Height(inches)'])
display(height_in)

Height(inches)
0                 74
1                 74
2                 72
3                 72
4                 73
...              ...
1029              73
1030              74
1031              75
1032              75
1033              73

[1034 rows x 1 columns]

In [7]:
weight_lb = pd.read_csv('DataMLB.csv', usecols=['Weight(pounds)'])
display(weight_lb)

Weight(pounds)
0              180.0
1              215.0
2              210.0
3              210.0
4              188.0
...              ...
1029           190.0
1030           180.0
1031           205.0
1032           190.0
1033           195.0

[1034 rows x 1 columns]

In [8]:
# Import numpy
import numpy as np

In [9]:
# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[[74]
 [74]
 [72]
 ...
 [75]
 [75]
 [73]]
[[1.8796]
 [1.8796]
 [1.8288]
 ...
 [1.905 ]
 [1.905 ]
 [1.8542]]


In [10]:
# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

[[23.11037639]
 [27.60406069]
 [28.48080465]
 ...
 [25.62295933]
 [23.74810865]
 [25.72686361]]


In [11]:
# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


In [12]:
# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

[195.]
[[73]
 [72]
 [74]
 [73]
 [74]
 [72]
 [73]
 [69]
 [72]
 [73]
 [75]]


In [13]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]


# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [14]:
# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [15]:
baseball = pd.read_csv('DataMLB.csv')
baseball.head()

Name Team       Position  Height(inches)  Weight(pounds)    Age
0    Adam_Donachie  BAL        Catcher              74           180.0  22.99
1        Paul_Bako  BAL        Catcher              74           215.0  34.69
2  Ramon_Hernandez  BAL        Catcher              72           210.0  30.78
3     Kevin_Millar  BAL  First_Baseman              72           210.0  35.43
4      Chris_Gomez  BAL  First_Baseman              73           188.0  35.71

In [16]:
# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[:50])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

[['Adam_Donachie' 'BAL' 'Catcher' 74 180.0 22.99]
 ['Paul_Bako' 'BAL' 'Catcher' 74 215.0 34.69]
 ['Ramon_Hernandez' 'BAL' 'Catcher' 72 210.0 30.78]
 ['Kevin_Millar' 'BAL' 'First_Baseman' 72 210.0 35.43]
 ['Chris_Gomez' 'BAL' 'First_Baseman' 73 188.0 35.71]
 ['Brian_Roberts' 'BAL' 'Second_Baseman' 69 176.0 29.39]
 ['Miguel_Tejada' 'BAL' 'Shortstop' 69 209.0 30.77]
 ['Melvin_Mora' 'BAL' 'Third_Baseman' 71 200.0 35.07]
 ['Aubrey_Huff' 'BAL' 'Third_Baseman' 76 231.0 30.19]
 ['Adam_Stern' 'BAL' 'Outfielder' 71 180.0 27.05]
 ['Jeff_Fiorentino' 'BAL' 'Outfielder' 73 188.0 23.88]
 ['Freddie_Bynum' 'BAL' 'Outfielder' 73 180.0 26.96]
 ['Nick_Markakis' 'BAL' 'Outfielder' 74 185.0 23.29]
 ['Brandon_Fahey' 'BAL' 'Outfielder' 74 160.0 26.11]
 ['Corey_Patterson' 'BAL' 'Outfielder' 69 180.0 27.55]
 ['Jay_Payton' 'BAL' 'Outfielder' 70 185.0 34.27]
 ['Jay_Gibbons' 'BAL' 'Designated_Hitter' 72 197.0 30.0]
 ['Erik_Bedard' 'BAL' 'Starting_Pitcher' 73 189.0 27.99]
 ['Hayden_Penn' 'BAL' 'Starting_Pitcher' 75

In [17]:
# Print out height of 124th player
print(np_baseball[124, 4])

220.0


In [18]:
# updated is available as 2D numpy array
updated = np.array(bmi)
print(updated)

[[23.11037639]
 [27.60406069]
 [28.48080465]
 ...
 [25.62295933]
 [23.74810865]
 [25.72686361]]


In [19]:
# Create np_baseball (3 cols)
baseball = pd.read_csv('DataMLB.csv', usecols=['Height(inches)', 'Weight(pounds)', 'Age'])
np_baseball = np.array(baseball)

In [20]:
# Print out addition of np_baseball and updated
print(np_baseball + updated)

[[ 97.11037639 203.11037639  46.10037639]
 [101.60406069 242.60406069  62.29406069]
 [100.48080465 238.48080465  59.26080465]
 ...
 [100.62295933 230.62295933  50.81295933]
 [ 98.74810865 213.74810865  54.75810865]
 [ 98.72686361 220.72686361  53.64686361]]


In [21]:
# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]


In [22]:
# Create np_height_in from np_baseball
np_height_in = np.array(np_baseball[:,0])

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

73.6972920696325
74.0


In [23]:
data = pd.read_csv('DataMLB.csv', usecols=['Height(inches)', 'Weight(pounds)', 'Age'])
data.head()

Height(inches)  Weight(pounds)    Age
0              74           180.0  22.99
1              74           215.0  34.69
2              72           210.0  30.78
3              72           210.0  35.43
4              73           188.0  35.71

In [24]:
# Print mean height (first column)
np_baseball = np.array(data)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

Average: 73.6972920696325
Median: 74.0
Standard Deviation: 2.304703041620148


In [25]:
# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,2])
print("Correlation: " + str(corr))

Correlation: [[ 1.         -0.07367013]
 [-0.07367013  1.        ]]


In [26]:
baseball = pd.read_csv('DataMLB.csv')
baseball.head()

Name Team       Position  Height(inches)  Weight(pounds)    Age
0    Adam_Donachie  BAL        Catcher              74           180.0  22.99
1        Paul_Bako  BAL        Catcher              74           215.0  34.69
2  Ramon_Hernandez  BAL        Catcher              72           210.0  30.78
3     Kevin_Millar  BAL  First_Baseman              72           210.0  35.43
4      Chris_Gomez  BAL  First_Baseman              73           188.0  35.71

In [37]:
positions = pd.read_csv('DataMLB.csv', usecols=['Position'])
heights = pd.read_csv('DataMLB.csv', usecols=['Height(inches)'])

In [38]:
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
catcher_heights = np_heights[np_positions == 'Catcher']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'Catcher']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of catchers: " + str(np.median(catcher_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of catchers: 73.0
Median height of other players: 74.0
